export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",


    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',


    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL',

    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export const nxbConstant = {
    CREATE_NXB_REQUEST: 'CREATE_NXB_REQUEST',
    CREATE_NXB_SUCCESS: 'CREATE_NXB_SUCCESS',
    CREATE_NXB_FAIL: 'CREATE_NXB_FAIL',


    GET_NXB_REQUEST: 'GET_NXB_REQUEST',
    GET_NXB_SUCCESS: 'GET_NXB_SUCCESS',
    GET_NXB_FAIL: 'GET_NXB_FAIL',

    DELETE_NXB_REQUEST: 'DELETE_NXB_REQUEST',
    DELETE_NXB_SUCCESS: 'DELETE_NXB_SUCCESS',
    DELETE_NXB_FAIL: 'DELETE_NXB_FAIL'
}


export const bookConstant = {
    CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAIL: 'CREATE_BOOK_FAIL',

    GET_ALL_BOOK_REQUEST: 'GET_ALL_BOOK_REQUEST',
    GET_ALL_BOOK_SUCCESS: 'GET_ALL_BOOK_SUCCESS',
    GET_ALL_BOOK_FAIL: 'GET_ALL_BOOK_FAIL',

    DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAIL: 'DELETE_BOOK_FAIL',



}


export const ticketBorrowedConstant = {
    CREATE_NEW_TICKET_BORROWED_REQUEST: 'CREATE_NEW_TICKET_BORROWED_REQUEST',
    CREATE_NEW_TICKET_BORROWED_SUCCESS: 'CREATE_NEW_TICKET_BORROWED_SUCCESS',
    CREATE_NEW_TICKET_BORROWED_FAIL: 'CREATE_NEW_TICKET_BORROWED_FAIL',


    GET_ALL_TICKET_REQUEST: 'GET_ALL_TICKET_REQUEST',
    GET_ALL_TICKET_SUCCESS: 'GET_ALL_TICKET_SUCCESS',
    GET_ALL_TICKET_FAIL: 'GET_ALL_TICKET_FAIL',

    RETURN_BOOK_REQUEST: 'RETURN_BOOK_REQUEST',
    RETURN_BOOK_SUCCESS: 'RETURN_BOOK_SUCCESS',
    RETURN_BOOK_FAIL: 'RETURN_BOOK_FAIL'
}

export const categoryConstants = {
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAIL: 'CREATE_CATEGORY_FAIL',

    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS ',
    GET_ALL_CATEGORY_FAIL: 'GET_ALL_CATEGORY_FAIL'
}

export const blogConstants = {
    CREATE_BLOG_REQUEST: 'CREATE_BLOG_REQUEST',
    CREATE_BLOG_SUCCESS: 'CREATE_BLOG_SUCCESS',
    CREATE_BLOG_FAIL: 'CREATE_BLOG_FAIL',


    GET_ALL_BLOG_REQUEST: 'GET_ALL_BLOG_REQUEST',
    GET_ALL_BLOG_SUCCESS: 'GET_ALL_BLOG_SUCCESS',
    GET_ALL_BLOG_FAIL: 'GET_ALL_BLOG_FAIL'
}

export const medical = {
    CREATE_NEW_PROFILE_REQUEST: 'CREATE_NEW_PROFILE_REQUEST',
    CREATE_NEW_PROFILE_SUCCESS: 'CREATE_NEW_PROFILE_SUCCESS',
    CREATE_NEW_PROFILE_FAIL: 'CREATE_NEW_PROFILE_FAIL',


    GET_ALL_PROFILE_REQUEST: 'GET_ALL_PROFILE_REQUEST',
    GET_ALL_PROFILE_SUCCESS: 'GET_ALL_PROFILE_SUCCESS',
    GET_ALL_PROFILE_FAIL: 'GET_ALL_PROFILE_FAIL',


    DELETE_PROFILE_REQUEST: 'DELETE_PROFILE_REQUEST',
    DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
    DELETE_PROFILE_FAIL: 'DELETE_PROFILE_FAIL'

}