export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",


    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    ADD_USER_REQUEST: 'ADD_USER_REQUEST',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_FAIL: 'ADD_USER_FAIL',


    GET_ALL_USER_REQUEST: 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL'
};

export const nxbConstant = {
    CREATE_NXB_REQUEST: 'CREATE_NXB_REQUEST',
    CREATE_NXB_SUCCESS: 'CREATE_NXB_SUCCESS',
    CREATE_NXB_FAIL: 'CREATE_NXB_FAIL',


    GET_NXB_REQUEST: 'GET_NXB_REQUEST',
    GET_NXB_SUCCESS: 'GET_NXB_SUCCESS',
    GET_NXB_FAIL: 'GET_NXB_FAIL',

    DELETE_NXB_REQUEST: 'DELETE_NXB_REQUEST',
    DELETE_NXB_SUCCESS: 'DELETE_NXB_SUCCESS',
    DELETE_NXB_FAIL: 'DELETE_NXB_FAIL'
}


export const bookConstant = {
    CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAIL: 'CREATE_BOOK_FAIL',

    GET_ALL_BOOK_REQUEST: 'GET_ALL_BOOK_REQUEST',
    GET_ALL_BOOK_SUCCESS: 'GET_ALL_BOOK_SUCCESS',
    GET_ALL_BOOK_FAIL: 'GET_ALL_BOOK_FAIL',

    DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAIL: 'DELETE_BOOK_FAIL',
}